from __future__ import annotations

import re


PHRASES: list[tuple[str, str]] = [
    ("this item is immune to freeze, slow and destroy.", "此物品免疫冻结、减速与摧毁。"),
    ("this has double damage bonus and double cooldown reduction.", "此物伤害加成与冷却缩减均翻倍。"),
    ("this has double crit chance bonus.", "此物暴击几率加成翻倍。"),
    ("this has double damage bonus.", "此物伤害加成翻倍。"),
    ("this has double charge amount.", "此物充能数值翻倍。"),
    ("this has +1 multicast.", "此物获得 +1 多重施放。"),
    ("this has +50% crit chance.", "此物获得 +50% 暴击几率。"),
    ("this has double damage.", "此物伤害翻倍。"),
    ("this has double value.", "此物价值翻倍。"),
    ("this hastes for twice as long.", "此物施加的迅捷持续时间翻倍。"),
    ("this slows for twice as long.", "此物施加的减速持续时间翻倍。"),
    ("this freezes for twice as long.", "此物施加的冻结持续时间翻倍。"),
    ("adjacent items are affected by freeze and slow for half as long.", "相邻物品受到的冻结与减速持续时间减半。"),
    ("the weapon to the right of this is affected by freeze and slow for half as long.", "此物右侧武器受到的冻结与减速持续时间减半。"),
    ("the weapon to the left of this is affected by freeze and slow for half as long.", "此物左侧武器受到的冻结与减速持续时间减半。"),
    ("your items are affected by freeze and slow for half as long.", "你的物品受到的冻结与减速持续时间减半。"),
    ("when you crit with an adjacent item, slow 2 item for 1 second(s).", "当你用相邻物品暴击时，减速 2 个物品，持续 1 秒。"),
    ("when you crit with an adjacent item, freeze 2 item for 0.5 second(s).", "当你用相邻物品暴击时，冻结 2 个物品，持续 0.5 秒。"),
    ("when you crit with an adjacent item, haste 2 item for 1 second(s).", "当你用相邻物品暴击时，迅捷 2 个物品，持续 1 秒。"),
    ("when you crit with an adjacent item, slow an item for 2 second(s).", "当你用相邻物品暴击时，减速 1 个物品，持续 2 秒。"),
    ("when you crit with an adjacent item, freeze an item for 1 second(s).", "当你用相邻物品暴击时，冻结 1 个物品，持续 1 秒。"),
    ("when you crit with an adjacent item, haste an item for 2 second(s).", "当你用相邻物品暴击时，迅捷 1 个物品，持续 2 秒。"),
    ("when you crit with an adjacent item, shield 40.", "当你用相邻物品暴击时，获得 40 护盾。"),
    ("when you crit with an adjacent item, heal 40.", "当你用相邻物品暴击时，治疗 40。"),
    ("when you crit with an adjacent item, poison 4.", "当你用相邻物品暴击时，施加 4 毒性。"),
    ("when you crit with an adjacent item, burn 4.", "当你用相邻物品暴击时，施加 4 燃烧。"),
    ("when you crit with an adjacent item, deal 40 damage.", "当你用相邻物品暴击时，造成 40 伤害。"),
    ("when you use an adjacent shield item, it gains +12 shield for the fight.", "当你使用相邻护盾物品时，其本场战斗获得 +12 护盾。"),
    ("when you use an adjacent heal item, it gains +12 heal for the fight.", "当你使用相邻治疗物品时，其本场战斗获得 +12 治疗。"),
    ("when you use an adjacent poison item, it gains +1 poison for the fight.", "当你使用相邻毒性物品时，其本场战斗获得 +1 毒性。"),
    ("when you use an adjacent burn item, it gains +1 burn for the fight.", "当你使用相邻燃烧物品时，其本场战斗获得 +1 燃烧。"),
    ("when you use the ammo item to the right of this, shield 10.", "当你使用此物右侧的弹药物品时，获得 10 护盾。"),
    ("when you use the ammo item to the right of this, heal 10.", "当你使用此物右侧的弹药物品时，治疗 10。"),
    ("when you use the ammo item to the right of this, poison 1.", "当你使用此物右侧的弹药物品时，施加 1 毒性。"),
    ("when you use the ammo item to the right of this, burn 1.", "当你使用此物右侧的弹药物品时，施加 1 燃烧。"),
    ("when you use the ammo item to the right of this, deal 10 damage.", "当你使用此物右侧的弹药物品时，造成 10 伤害。"),
    ("the ammo item to the right of this gains +25% crit chance for the fight", "此物右侧的弹药物品本场战斗获得 +25% 暴击几率"),
    ("adjacent friends have +50% crit chance.", "相邻随从获得 +50% 暴击几率。"),
    ("shield 10 for each aquatic or toy item you have", "你每拥有一件水生或玩具物品，获得 10 护盾"),
    ("heal 15 for each aquatic or toy item you have", "你每拥有一件水生或玩具物品，治疗 15"),
    ("poison 1 for each aquatic or toy item you have", "你每拥有一件水生或玩具物品，施加 1 毒性"),
    ("burn 1 for each aquatic or toy item you have", "你每拥有一件水生或玩具物品，施加 1 燃烧"),
    ("deal 10 damage for each aquatic or toy item you have", "你每拥有一件水生或玩具物品，造成 10 伤害"),
    ("this has double max ammo bonus.", "此物最大弹药加成翻倍。"),
    ("adjacent ammo items have +25% crit chance.", "相邻弹药物品获得 +25% 暴击几率。"),
    ("adjacent ammo items have +40% crit chance.", "相邻弹药物品获得 +40% 暴击几率。"),
    ("adjacent ammo items are affected by freeze and slow for half as long.", "相邻弹药物品受到的冻结与减速持续时间减半。"),
    ("adjacent weapons have +20 damage.", "相邻武器获得 +20 伤害。"),
    ("if both adjacent items are aquatic, they have 50% crit chance.", "若两侧相邻物品均为水生，则它们获得 50% 暴击几率。"),
    ("adjacent aquatic items have +25% crit chance.", "相邻水生物品获得 +25% 暴击几率。"),
    ("the first time you fall below half health each fight, slow 4 items for 4 second(s).", "每场战斗首次生命降至一半以下时，减速 4 个物品，持续 4 秒。"),
    ("the first time you fall below half health each fight, freeze 2 items for 4 second(s).", "每场战斗首次生命降至一半以下时，冻结 2 个物品，持续 4 秒。"),
    ("the first time you fall below half health each fight, haste 4 items for 4 second(s).", "每场战斗首次生命降至一半以下时，迅捷 4 个物品，持续 4 秒。"),
    ("the first time you fall below half health each fight, heal equal to 10% of your max health.", "每场战斗首次生命降至一半以下时，治疗量等于你最大生命值的 10%。"),
    ("this has double xp bonus.", "此物经验加成翻倍。"),
    ("when you use an item from another hero, slow an item for 2 second(s).", "当你使用来自其他英雄的物品时，减速 1 个物品，持续 2 秒。"),
    ("when you use an item from another hero, freeze an item for 1 second(s).", "当你使用来自其他英雄的物品时，冻结 1 个物品，持续 1 秒。"),
    ("when you use an item from another hero, haste it for 2 second(s).", "当你使用来自其他英雄的物品时，对其施加迅捷，持续 2 秒。"),
    ("when you use an item from another hero, shield 20.", "当你使用来自其他英雄的物品时，获得 20 护盾。"),
    ("when you use an item from another hero, heal 20.", "当你使用来自其他英雄的物品时，治疗 20。"),
    ("when you use an item from another hero, poison 2.", "当你使用来自其他英雄的物品时，施加 2 毒性。"),
    ("when you use an item from another hero, burn 2.", "当你使用来自其他英雄的物品时，施加 2 燃烧。"),
    ("when you use an item from another hero, deal 20 damage.", "当你使用来自其他英雄的物品时，造成 20 伤害。"),
    ("your items from other heroes are affected by freeze and slow for half as long.", "你来自其他英雄的物品受到的冻结与减速持续时间减半。"),
    ("this has double bonus damage and double cooldown reduction.", "此物伤害加成与冷却缩减均翻倍。"),
    ("shield 20 for each non-weapon item you have", "你每拥有一件非武器物品，获得 20 护盾"),
    ("heal 20 for each non-weapon item you have", "你每拥有一件非武器物品，治疗 20"),
    ("poison 2 for each non-weapon item you have", "你每拥有一件非武器物品，施加 2 毒性"),
    ("burn 2 for each non-weapon item you have", "你每拥有一件非武器物品，施加 2 燃烧"),
    ("deal 20 damage for each non-weapon item you have", "你每拥有一件非武器物品，造成 20 伤害"),
    ("your non-weapon items gain +30% crit chance for the fight", "本场战斗中，你的非武器物品获得 +30% 暴击几率"),
    ("your weapons have double crit damage.", "你的武器造成双倍暴击伤害。"),
    ("if you have two or fewer weapons, they have lifesteal.", "若你拥有两件或更少武器，则它们拥有生命偷取。"),
    ("your weapons are affected by freeze and slow for half as long.", "你的武器受到的冻结与减速持续时间减半。"),
    ("enemy items have -50% crit chance.", "敌人物品的暴击几率 -50%。"),
    ("shield equal to triple this item's damage", "获得护盾，数值为此物品伤害的三倍"),
    ("heal equal to triple this item's damage", "治疗量等于此物品伤害的三倍"),
    ("slow all enemy items for 3 second(s)", "减速全部敌人物品，持续 3 秒"),
    ("freeze all enemy items for 1 second(s)", "冻结全部敌人物品，持续 1 秒"),
    ("this has double charge.", "此物充能翻倍。"),
    ("adjacent friends have +1 multicast.", "相邻随从获得 +1 多重施放。"),
    ("shield 10 for each unique type you have", "你每拥有一种独特类型，获得 10 护盾"),
    ("heal 10 for each unique type you have", "你每拥有一种独特类型，治疗 10"),
    ("poison 1 for each unique type you have", "你每拥有一种独特类型，施加 1 毒性"),
    ("burn 1 for each unique type you have", "你每拥有一种独特类型，施加 1 燃烧"),
    ("deal 10 damage for each each unique type you have", "你每拥有一种独特类型，造成 10 伤害"),
    ("your items have +5% crit chance for each unique type you have.", "你每拥有一种独特类型，物品获得 +5% 暴击几率。"),
    ("the first time you use an item each fight, slow all enemy items for 1 second(s).", "每场战斗首次使用物品时，减速全部敌人物品，持续 1 秒。"),
    ("the first time you use an item each fight, freeze all enemy items for 0.5 second(s).", "每场战斗首次使用物品时，冻结全部敌人物品，持续 0.5 秒。"),
    ("the first time you use an item each fight, haste all your items for 1 second(s).", "每场战斗首次使用物品时，迅捷你的全部物品，持续 1 秒。"),
    ("the first time you use an item each fight, shield equal to 20% of your max health.", "每场战斗首次使用物品时，获得等于最大生命值 20% 的护盾。"),
    ("the first time you use an item each fight, heal equal to 20% of your max health.", "每场战斗首次使用物品时，治疗量等于最大生命值的 20%。"),
    ("the first time you use an item each fight, poison equal to 5% of your max health.", "每场战斗首次使用物品时，施加等于最大生命值 5% 的毒性。"),
    ("the first time you use an item each fight, burn equal to 5% of your max health.", "每场战斗首次使用物品时，施加等于最大生命值 5% 的燃烧。"),
    ("the first time you use an item each fight, it gains +100% crit chance for the fight.", "每场战斗首次使用物品时，该物品本场战斗获得 +100% 暴击几率。"),
    ("the first time you use an item each fight, deal damage equal to 20% of your max health.", "每场战斗首次使用物品时，造成等于最大生命值 20% 的伤害。"),
    ("you can use an item a second time instead.", "你可以改为再使用一次物品。"),
    ("at the start of each fight, your items become immune to freeze, slow and destroy for 6 seconds.", "每场战斗开始时，你的物品免疫冻结、减速与摧毁，持续 6 秒。"),
    ("at the start of each fight, your other small items become immune to freeze, slow and destroy for 6 seconds.", "每场战斗开始时，你的其他小型物品免疫冻结、减速与摧毁，持续 6 秒。"),
    ("at the start of each fight, slow 2 enemy items for 2 second(s).", "每场战斗开始时，减速 2 个敌人物品，持续 2 秒。"),
    ("this hastes twice.", "此物施加两次迅捷。"),
    ("this has double multicast bonus.", "此物多重施放加成翻倍。"),
    ("your aquatic items are affected by freeze and slow for half as long.", "你的水生物品受到的冻结与减速持续时间减半。"),
    ("the item to the right of this is affected by freeze and slow for half as long.", "此物右侧物品受到的冻结与减速持续时间减半。"),
    ("this has double damage bonus", "此物伤害加成翻倍"),
    ("this has half slow duration.", "此物减速持续时间减半。"),
    ("adjacent shield items have +20 shield.", "相邻护盾物品获得 +20 护盾。"),
    ("adjacent poison items have +3 poison.", "相邻毒性物品获得 +3 毒性。"),
    ("adjacent burn items have +2 burn.", "相邻燃烧物品获得 +2 燃烧。"),
    ("the weapon to the right of this has + damage equal to its crit chance.", "此物右侧武器获得等于其暴击几率的额外伤害。"),
    ("when you use an ammo item, slow an item for 1 second(s)", "当你使用弹药物品时，减速 1 个物品，持续 1 秒"),
    ("when yo uuse an ammo item, slow an item for 1 second(s)", "当你使用弹药物品时，减速 1 个物品，持续 1 秒"),
    ("poison yourself 1.", "对自己施加 1 毒性。"),
    ("reduce the cooldown of your other items by 8% for the fight", "本场战斗中，你的其他物品冷却缩短 8%"),
    ("increase this item's cooldown by 1 second(s) for each non-friend you have for the fight.", "本场战斗中，你每拥有一个非随从，此物冷却增加 1 秒。"),
    ("increase this item's cooldown by 4 second(s) for the fight", "本场战斗中，此物冷却增加 4 秒"),
    ("increase this item's cooldown by 3 second(s) for the fight", "本场战斗中，此物冷却增加 3 秒"),
    ("increase this item's cooldown by 2 second(s) for the fight", "本场战斗中，此物冷却增加 2 秒"),
    ("when you freeze, adjacent poison items gain +2 poison for the fight.", "当你冻结时，相邻毒性物品本场战斗获得 +2 毒性。"),
    ("when you freeze, adjacent poison items gain +4 poison for the fight.", "当你冻结时，相邻毒性物品本场战斗获得 +4 毒性。"),
    ("when you freeze, adjacent poison items gain +6 poison for the fight.", "当你冻结时，相邻毒性物品本场战斗获得 +6 毒性。"),
    ("when you freeze, adjacent poison items gain +8 poison for the fight.", "当你冻结时，相邻毒性物品本场战斗获得 +8 毒性。"),
    ("when this is reloaded, it gains +40 damage for the fight", "当此物被装填时，本场战斗获得 +40 伤害"),
    ("when this is reloaded, it gains +60 damage for the fight", "当此物被装填时，本场战斗获得 +60 伤害"),
    ("when this is reloaded, it gains +80 damage for the fight", "当此物被装填时，本场战斗获得 +80 伤害"),
    ("when you burn with an adjacent item, reload this and it gains +25 damage for the fight.", "当你用相邻物品施加燃烧时，装填此物，并使其本场战斗获得 +25 伤害。"),
    ("when you burn with an adjacent item, reload this and it gains +50 damage for the fight.", "当你用相邻物品施加燃烧时，装填此物，并使其本场战斗获得 +50 伤害。"),
    ("when you burn with an adjacent item, reload this and it gains +75 damage for the fight.", "当你用相邻物品施加燃烧时，装填此物，并使其本场战斗获得 +75 伤害。"),
    ("...and enchant the item with golden if able.", "……并尽可能为该物品附加金色附魔。"),
    ("...and enchant the item with heavy if able.", "……并尽可能为该物品附加沉重附魔。"),
    ("...and enchant the item with icy if able.", "……并尽可能为该物品附加冰冷附魔。"),
    ("...and enchant the item with turbo if able.", "……并尽可能为该物品附加涡轮附魔。"),
    ("...and enchant the item with shielded if able.", "……并尽可能为该物品附加护盾附魔。"),
    ("...and enchant the item with restorative if able.", "……并尽可能为该物品附加恢复附魔。"),
    ("...and enchant the item with toxic if able.", "……并尽可能为该物品附加剧毒附魔。"),
    ("...and enchant the item with fiery if able.", "……并尽可能为该物品附加炽热附魔。"),
    ("...and enchant the item with shiny if able.", "……并尽可能为该物品附加闪亮附魔。"),
    ("...and enchant the item with deadly if able.", "……并尽可能为该物品附加致命附魔。"),
    ("...and enchant the item with radiant if able.", "……并尽可能为该物品附加光辉附魔。"),
    ("...and enchant the item with obsidian if able.", "……并尽可能为该物品附加黑曜石附魔。"),
    ("slow 2 items for 1 second(s)", "减速 2 个物品，持续 1 秒"),
    ("haste 2 items for 1 second(s)", "迅捷 2 个物品，持续 1 秒"),
    ("freeze an item for 1 second(s)", "冻结 1 个物品，持续 1 秒"),
    ("at the start of each day", "每天开始时"),
    ("at the start of each fight", "每场战斗开始时"),
    ("at the start of each hour", "每小时开始时"),
    ("this deals double crit damage", "此物造成双倍暴击伤害"),
    ("the first time you would be defeated each fight", "每场战斗首次即将战败时"),
    ("you take no damage for the first", "你在前"),
    ("or until you use an item", "或直到你使用一件物品"),
    ("when you win a fight against a hero", "当你战胜一名英雄"),
    ("when you win a fight with this", "当你携带此物获胜"),
    ("when you win a fight", "当你赢得一场战斗"),
    ("when you buy another aquatic item", "当你购买另一件水生物品"),
    ("when you buy an aquatic item", "当你购买一件水生物品"),
    ("when you buy this", "当你购买此物"),
    ("when you sell an item", "当你出售一件物品"),
    ("when you gain gold", "当你获得金币"),
    ("when you reload an item", "当你装填一件物品"),
    ("when you use an adjacent aquatic item", "当你使用相邻的水生物品"),
    ("when you use an adjacent weapon", "当你使用相邻的武器"),
    ("when you use an adjacent item", "当你使用相邻物品"),
    ("when you use another aquatic or ammo item", "当你使用另一件水生或弹药物品"),
    ("when you use another aquatic item", "当你使用另一件水生物品"),
    ("when you use another ammo item", "当你使用另一件弹药物品"),
    ("when you use another friend", "当你使用另一个随从"),
    ("when you use another weapon or haste", "当你使用另一件武器或施加迅捷"),
    ("when you use another weapon", "当你使用另一件武器"),
    ("when you use another non-weapon item", "当你使用另一件非武器物品"),
    ("when you use an ammo item", "当你使用一件弹药物品"),
    ("when you use an aquatic item", "当你使用一件水生物品"),
    ("when you use a flying item", "当你使用一件飞行物品"),
    ("when you use a friend", "当你使用一个随从"),
    ("when you use a weapon", "当你使用一件武器"),
    ("when you use the weapon to the left of this", "当你使用此物左侧的武器"),
    ("when you use the weapon to the right of this", "当你使用此物右侧的武器"),
    ("when you use this", "当你使用此物"),
    ("when you crit with another item", "当你用另一件物品暴击"),
    ("when you crit with the item to the right of this", "当你用此物右侧的物品暴击"),
    ("when you crit with this", "当你用此物暴击"),
    ("when you crit with it", "当你用它暴击"),
    ("when you poison, freeze, or burn", "当你施加毒性、冻结或燃烧"),
    ("when you haste or slow", "当你施加迅捷或减速"),
    ("when you slow or crit", "当你减速或暴击"),
    ("when you freeze", "当你冻结"),
    ("when you haste", "当你施加迅捷"),
    ("when you slow", "当你减速"),
    ("when you burn", "当你燃烧"),
    ("when you poison", "当你施加毒性"),
    ("when you crit", "当你暴击"),
    ("when this is hasted", "当此物获得迅捷时"),
    ("when an enemy uses an item", "当敌人使用一件物品"),
    ("when an enemy uses their leftmost item", "当敌人使用其最左侧物品"),
    ("if this is your only friend", "若此为你唯一的随从"),
    ("if this is adjacent to a poison item", "若此物与毒性物品相邻"),
    ("if this is adjacent to a slow item", "若此物与减速物品相邻"),
    ("if you have 5 or more unique types", "若你拥有 5 种或更多不同类型"),
    ("if you have a vehicle or large item", "若你拥有载具或大型物品"),
    ("if you have another vehicle or large item", "若你拥有另一件载具或大型物品"),
    ("if you have another tech item", "若你拥有另一件科技物品"),
    ("if you have another tool, property, friend, ammo or relic item", "若你拥有另一件工具、地产、随从、弹药或遗物"),
    ("if you have another item with burn, poison, slow, or freeze", "若你拥有另一件带燃烧、毒性、减速或冻结的物品"),
    ("if you have exactly one weapon", "若你恰好拥有一件武器"),
    ("if the item is large", "若该物品为大型"),
    ("if it is your only weapon", "若此为你唯一的武器"),
    ("the cooldowns of aquatic items to the left of this", "此物左侧水生物品的冷却"),
    ("the weapon to the left of this", "此物左侧的武器"),
    ("the weapon to the right of this", "此物右侧的武器"),
    ("the item to the right of this", "此物右侧的物品"),
    ("weapons to the right of this", "此物右侧的武器"),
    ("aquatic items to the left of this", "此物左侧的水生物品"),
    ("adjacent items'", "相邻物品的"),
    ("adjacent items", "相邻物品"),
    ("this and adjacent weapons", "此物与相邻武器"),
    ("your other weapons", "你的其他武器"),
    ("your aquatic items", "你的水生物品"),
    ("your shield items", "你的护盾物品"),
    ("your weapons", "你的武器"),
    ("your poison items", "你的毒性物品"),
    ("your burn items", "你的燃烧物品"),
    ("your tools and vehicles", "你的工具和载具"),
    ("your small items", "你的小型物品"),
    ("your other items", "你的其他物品"),
    ("your items from other heroes", "你来自其他英雄的物品"),
    ("your items have +", "你的物品获得 +"),
    ("your items", "你的物品"),
    ("this has +", "此物获得 +"),
    ("this has", "此物拥有"),
    ("have +", "获得 +"),
    ("has +", "获得 +"),
    ("your other", "你的其他"),
    ("this item's cooldown", "此物品冷却"),
    ("this item's damage", "此物品伤害"),
    ("this item's value", "此物品价值"),
    ("this item's ammo", "此物品弹药"),
    ("an enemy's max health", "敌人的最大生命"),
    ("an enemy item's cooldown", "一件敌方物品的冷却"),
    ("charge adjacent items", "为相邻物品充能"),
    ("charge them", "为它们充能"),
    ("charge this", "为此物充能"),
    ("charge a non-weapon item", "为一件非武器物品充能"),
    ("haste adjacent items", "使相邻物品获得迅捷"),
    ("haste an adjacent item", "使一件相邻物品获得迅捷"),
    ("haste an item", "使一件物品获得迅捷"),
    ("haste the aquatic item to the right of this", "使此物右侧的水生物品获得迅捷"),
    ("haste your tools and vehicles", "使你的工具和载具获得迅捷"),
    ("haste your other items", "使你的其他物品获得迅捷"),
    ("haste your small items", "使你的小型物品获得迅捷"),
    ("slow an item", "减速一件物品"),
    ("freeze an item", "冻结一件物品"),
    ("freeze it", "冻结它"),
    ("slow it", "减速它"),
    ("reload adjacent ammo items", "为相邻弹药物品装填"),
    ("reload all your items", "为你的全部物品装填"),
    ("reload the item to the right of this", "为此物右侧物品装填"),
    ("reload your ammo items", "为你的弹药物品装填"),
    ("reload 1 ammo", "装填 1 点弹药"),
    ("spend all its ammo", "消耗其全部弹药"),
    ("deal damage equal to", "造成伤害，数值等于"),
    ("deal damage", "造成伤害"),
    ("this gains", "此物获得"),
    ("this has", "此物拥有"),
    ("this deals", "此物造成"),
    ("this is hasted", "此物获得迅捷"),
    ("permanently increase the damage bonus of this item by the amount gained", "永久将此物伤害加成提高，数值等于本次获得量"),
    ("permanently gains", "永久获得"),
    ("for the fight", "持续整场战斗"),
    ("of each fight", "每场战斗"),
    ("on its first use each fight", "每场战斗首次使用时"),
    ("and destroy this", "并摧毁此物"),
    ("destroy this and all smaller items", "摧毁此物及所有更小的物品"),
    ("destroy a small item", "摧毁一件小型物品"),
    ("get a small ammo item from any hero", "获得一件任意英雄的小型弹药物品"),
    ("get a small aquatic item", "获得一件小型水生物品"),
    ("get a small item from any hero", "获得一件任意英雄的小型物品"),
    ("get a piranha", "获得一条食人鱼"),
    ("get a coconut or citrus", "获得一个椰子或柑橘"),
    ("get a non-vanessa item", "获得一件非瓦内莎物品"),
    ("gain 1 additional xp", "额外获得 1 点经验"),
    ("gain 1 xp", "获得 1 点经验"),
    ("if you won the fight with this", "若你携带此物获胜"),
    ("you take no damage", "你不受伤害"),
    ("crit chance", "暴击几率"),
    ("crit damage", "暴击伤害"),
    ("max ammo", "最大弹药"),
    ("max health", "最大生命"),
    ("second(s)", "秒"),
    ("seconds", "秒"),
    ("second", "秒"),
    ("item(s)", "件物品"),
    ("lifesteal", "生命偷取"),
    ("multicast", "多重施放"),
    ("cooldown", "冷却"),
    ("reduced by", "减少"),
    ("increase this item's", "提高此物品的"),
    ("increase an enemy item's", "提高一件敌方物品的"),
    ("are reduced by", "减少"),
    ("is reduced by", "减少"),
    ("is halved", "减半"),
    ("double the damage gain", "伤害提升翻倍"),
    ("equal to this", "等于此物"),
    ("equal to", "等于"),
    ("for each adjacent friend or property", "每有一个相邻随从或地产"),
    ("for each adjacent friend or ray", "每有一个相邻随从或射线"),
    ("for each adjacent aquatic item", "每有一件相邻水生物品"),
    ("for each adjacent friend", "每有一个相邻随从"),
    ("for each other aquatic item you have", "你每拥有一件其他水生物品"),
    ("for each friend you have", "你每拥有一个随从"),
    ("for each aquatic item you have", "你每拥有一件水生物品"),
    ("for each non-friend you have", "你每拥有一个非随从"),
    ("for each", "每有一个"),
    ("times more damage", "倍伤害"),
    ("times this item's value", "倍此物品价值"),
    ("times this item's", "倍此物品的"),
    ("sells apparel from any hero", "出售任意英雄的服饰"),
    ("sells toys from any hero", "出售任意英雄的玩具"),
    ("sells aquatic items", "出售水生物品"),
    ("sells burn items.", "出售燃烧物品。"),
    ("sells freeze items.", "出售冻结物品。"),
    ("sells haste items.", "出售迅捷物品。"),
    ("sells haste, slow and cooldown items.", "出售迅捷、减速和冷却物品。"),
    ("sells health and shield items", "出售生命与护盾物品"),
    ("sells large items", "出售大型物品"),
    ("sells poison items.", "出售毒性物品。"),
    ("sells slow items.", "出售减速物品。"),
    ("sells non-weapon items.", "出售非武器物品。"),
    ("sells small and large items. buys your medium items at", "出售小型与大型物品。以"),
    ("sells medium and large items. buys your small items at", "出售中型与大型物品。以"),
    ("sells small and medium items. buys your large items at", "出售小型与中型物品。以"),
    ("sells gold-tier items", "出售黄金品质物品"),
    ("sells silver-tier items", "出售白银品质物品"),
    ("sells diamond-tier items", "出售钻石品质物品"),
    ("sells enchanted items", "出售附魔物品"),
    ("sells medium items", "出售中型物品"),
    ("sells small items", "出售小型物品"),
    ("sells ammo items", "出售弹药物品"),
    ("sells weapons", "出售武器"),
    ("sells tools", "出售工具"),
    ("sells items. always sells discounted items.", "出售物品。始终以折扣出售。"),
    ("sells items.", "出售物品。"),
    ("buys your small items at", "以如下加成收购你的小型物品："),
    ("buys your medium items at", "以如下加成收购你的中型物品："),
    ("buys your large items at", "以如下加成收购你的大型物品："),
    ("always sells discounted items", "始终以折扣出售"),
    ("from any hero", "来自任意英雄"),
    ("from other heroes", "来自其他英雄"),
    ("that weapon has lifesteal", "该武器拥有生命偷取"),
    ("use this", "使用此物"),
    ("are aquatic in combat", "在战斗中视为水生"),
    ("are friends", "视为随从"),
    ("this has + multicast equal to its ammo", "此物的多重施放等于其弹药"),
    ("this has multicast equal to its current ammo", "此物的多重施放等于当前弹药"),
    ("this has +damage equal to its crit chance", "此物获得等于其暴击几率的伤害"),
    ("adjacent items have bonus damage, heal, or shield equal to their crit chance", "相邻物品获得等于其暴击几率的额外伤害、治疗或护盾"),
    ("a friend gains +1 multicast", "一个随从获得 +1 多重施放"),
    ("poison equal to this item's damage", "施加毒性，数值等于此物品伤害"),
    ("burn equal to 10% of this item's damage", "施加燃烧，数值为此物品伤害的 10%"),
    ("poison equal to 20% of this item's damage", "施加毒性，数值为此物品伤害的 20%"),
    ("shield equal to this item's ammo", "获得护盾，数值等于此物品弹药"),
    ("shield equal to this item's damage", "获得护盾，数值等于此物品伤害"),
    ("heal equal to", "治疗量等于"),
    ("shield equal to", "护盾量等于"),
    ("deal", "造成"),
    ("gain", "获得"),
    ("haste", "迅捷"),
    ("slow", "减速"),
    ("freeze", "冻结"),
    ("poison", "毒性"),
    ("burn", "燃烧"),
    ("shield", "护盾"),
    ("heal", "治疗"),
    ("regen", "再生"),
    ("reload", "装填"),
    ("ammo", "弹药"),
    ("damage", "伤害"),
    ("weapons", "武器"),
    ("weapon", "武器"),
    ("friends", "随从"),
    ("friend", "随从"),
    ("aquatic", "水生"),
    ("tools", "工具"),
    ("tool", "工具"),
    ("vehicles", "载具"),
    ("vehicle", "载具"),
    ("property", "地产"),
    ("relic", "遗物"),
    ("apparel", "服饰"),
    ("toys", "玩具"),
    ("toy", "玩具"),
    ("tech", "科技"),
    ("gold", "金币"),
    ("value", "价值"),
    ("items", "物品"),
    ("item", "物品"),
    ("small", "小型"),
    ("medium", "中型"),
    ("large", "大型"),
    ("this", "此物"),
    ("your", "你的"),
    ("and", "并且"),
    ("for", "持续"),
    ("with", "用"),
    ("each", "每"),
    ("fight", "战斗"),
    ("day", "天"),
]


TAG_ZH = {
    "Weapon": "武器",
    "Tool": "工具",
    "Friend": "随从",
    "Aquatic": "水生",
    "Vehicle": "载具",
    "Apparel": "服饰",
    "Food": "食物",
    "Potion": "药水",
    "Relic": "遗物",
    "Tech": "科技",
    "Toy": "玩具",
    "Property": "地产",
    "Ammo": "弹药",
    "Core": "核心",
    "Dragon": "龙",
    "Dinosaur": "恐龙",
    "Drone": "无人机",
    "Instrument": "乐器",
    "Loot": "战利品",
    "Merchant": "商人",
    "Ray": "射线",
    "Reagent": "试剂",
    "Trap": "陷阱",
}

ENCHANT_ZH = {
    "Golden": "金色",
    "Heavy": "沉重",
    "Icy": "冰冷",
    "Turbo": "涡轮",
    "Shielded": "护盾",
    "Restorative": "恢复",
    "Toxic": "剧毒",
    "Fiery": "炽热",
    "Shiny": "闪亮",
    "Deadly": "致命",
    "Radiant": "光辉",
    "Obsidian": "黑曜石",
}

EVENT_ZH = {
    "Roaming Isle": "漂流岛",
    "Tortuga": "托图加",
    "Treasure Turtle": "宝藏龟",
    "Wandering Shoal": "游荡浅滩",
    "Awakened Primordial": "觉醒元初体",
    "Prince Marianas": "马里亚纳王子",
    "Elite Duelist": "精英决斗者",
    "Preening Duelist": "自负决斗者",
    "Terrorform": "恐化体",
    "Bloodreef Captain": "血礁船长",
    "Radiant Corsair": "光辉海盗",
    "Boss Harrow": "哈罗首领",
    "Bloodreef Raider": "血礁掠夺者",
    "Ferros Khan": "费罗斯可汗",
    "Ventriloquist": "腹语师",
    "Trash Golem": "垃圾魔像",
    "Infernal Frigate": "炼狱护卫舰",
    "Bounty Hunter": "赏金猎人",
    "Hoverbike Hooligan": "悬浮摩托流氓",
    "Loan Shark": "放贷鲨鱼",
    "Morguloth": "莫古洛斯",
    "Flame Juggler": "火焰杂耍师",
    "Pyro": "火焰狂热者",
    "Ghost Pepper": "幽灵辣椒",
    "Coconut Crab": "椰子蟹",
    "Kyver Drone": "凯弗无人机",
    "Eight Arm Davvy": "八臂戴维",
    "Rex Spex": "雷克斯·斯佩克斯",
    "Frost Street Challenger": "霜街挑战者",
    "Tempest Bravo": "风暴勇士",
    "Bouncertron": "保镖机甲",
    "Outlands Dervish": "外域苦修者",
    "Covetous Thief": "贪婪窃贼",
    "Car Conductor": "列车长",
    "Cloudtop Admiral": "云顶上将",
    "Master Alchemist": "炼金大师",
    "Gibbus": "吉布斯",
    "Lord of the Wastes": "废土领主",
    "Mr. Moo": "穆先生",
    "Annex Trooper": "并吞步兵",
    "Volkas Enforcer": "沃尔卡斯执行者",
    "Frost Street Champion": "霜街冠军",
}


def _apply_phrases(text: str) -> str:
    result = text
    for en, zh in sorted(PHRASES, key=lambda item: len(item[0]), reverse=True):
        result = re.sub(re.escape(en), zh, result, flags=re.I)
    return result


def translate_en_to_zh(text: str) -> str:
    source = re.sub(r"\s+", " ", (text or "")).strip()
    if not source:
        return source

    def _enchant_able(match: re.Match[str]) -> str:
        name = match.group(1)
        canonical = next((key for key in ENCHANT_ZH if key.lower() == name.lower()), name)
        return f"……并尽可能为该物品附加{ENCHANT_ZH.get(canonical, canonical)}附魔。"

    # Resolve patterned sentences before short-word replacement.
    working = re.sub(
        r"\.\.\.and enchant the item with ([A-Za-z]+) if able\.",
        _enchant_able,
        source,
        flags=re.I,
    )
    working = re.sub(
        r"the first (\d+) times you crit with this each fight, you take no damage for (\d+(?:\.\d+)?) second(?:s)?\.?",
        r"每场战斗前 \1 次用此物暴击时，你免疫伤害，持续 \2 秒。",
        working,
        flags=re.I,
    )
    working = re.sub(
        r"if you have exactly one weapon, its cooldown is reduced by (\d+(?:\.\d+)?)%\.",
        r"若你恰好拥有一件武器，其冷却缩短 \1%。",
        working,
        flags=re.I,
    )
    working = re.sub(
        r"at the start of each fight, increase an enemy item's cooldown by (\d+) seconds? for the fight\.",
        r"每场战斗开始时，使一件敌人物品的冷却增加 \1 秒，持续整场战斗。",
        working,
        flags=re.I,
    )

    # Protect remaining enchantment proper nouns so short words like "shield" do not break "Shielded".
    protected: dict[str, str] = {}
    for index, name in enumerate(sorted(ENCHANT_ZH.keys(), key=len, reverse=True)):
        token = f"__ENCHANT_{index}__"
        pattern = re.compile(rf"\b{re.escape(name)}\b", re.I)
        if pattern.search(working):
            working = pattern.sub(token, working)
            protected[token] = ENCHANT_ZH[name]

    translated = _apply_phrases(working)
    translated = re.sub(
        r"the first (\d+) times you crit with this each fight",
        r"每场战斗前 \1 次用此物暴击时",
        translated,
        flags=re.I,
    )
    translated = re.sub(r"\bdouble\b", "双倍", translated, flags=re.I)
    translated = re.sub(r"\b(\d+(?:\.\d+)?)%", r"\1%", translated)
    for token, zh in protected.items():
        translated = translated.replace(token, zh)
    translated = re.sub(r"\s+", " ", translated).strip()
    translated = translated.replace(" .", "。").replace(" ,", "，")
    translated = re.sub(r"\s+。", "。", translated)
    return translated


def translate_tags(tags: list[str]) -> list[str]:
    return [TAG_ZH.get(tag, tag) for tag in tags or []]


def translate_enchant_name(name: str) -> str:
    return ENCHANT_ZH.get(name, name)


def translate_event_name(name: str) -> str:
    return EVENT_ZH.get(name, name)
